import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Data Tutor",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/images/DataTutorCircle.png",
        sizes: "32x32",
        type: "image/png"
      },
      {
        url: "/images/DataTutorCircle.png",
        sizes: "16x16",
        type: "image/png"
      }
    ],
    apple: {
      url: "/images/DataTutorCircle.png",
      sizes: "180x180",
      type: "image/png"
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${InterFont.variable} `}>
        <Providers>
          {children}
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
