import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

const InterFont = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Data Tutor",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/images/DataTutorCircle.png",
        sizes: "32x32"
      },
      {
        url: "/images/DataTutorCircle.png",
        sizes: "16x16"
      },
      {
        url: "/images/DataTutorCircle.png",
        sizes: "48x48"
      },
      {
        url: "/images/DataTutorCircle.png",
        sizes: "64x64"
      }
    ],
    shortcut: [
      {
        url: "/images/DataTutorCircle.png"
      }
    ],
    apple: [
      {
        url: "/images/DataTutorCircle.png",
        sizes: "180x180",
        type: "image/png"
      }
    ]
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/images/DataTutorCircle.png" sizes="any" />
        <link rel="shortcut icon" href="/images/DataTutorCircle.png" />
        <link rel="apple-touch-icon" href="/images/DataTutorCircle.png" />
      </head>
      <body className={`${InterFont.variable} `}>
        <Providers>
          {children}
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
